env:
  RUBY_VERSION: 2.7.2

name: Rails CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job_all:
    name: Rubocop + Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby ${{ env.RUBY_VERSION }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Bundle cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Setup database
        run:  |
          RAILS_ENV=test bundler exec rails db:create
          RAILS_ENV=test bundler exec rails db:migrate

      - name: Webpack compilation
        run: RAILS_ENV=test bundle exec rails webpacker:compile

      - name: Run Test
        run: RAILS_ENV=test bundler exec rails test
